apiVersion: batch/v1
kind: CronJob
metadata:
  name: helloworld
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
        template:
                spec:

                  containers:
                    - name: busybox
                      image: busybox
                      command: ["echo","hello"]

                  restartPolicy: Never
