# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-09-14T09:19:13Z"
  generation: 1
  labels:
    app: ngnix
  name: ngnix
  namespace: default
  resourceVersion: "77486"
  uid: 3d19adfb-7d1d-48c7-b874-d7679c400c3a
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ngnix
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ngnix
    spec:
      containers:
      - image: sushanth53/ngnix_server
        imagePullPolicy: Always
        name: ngnix-server-kn8cc
        resources:
          limits:
            cpu: "100m"
          requests:
            cpu: "5m" 
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-09-14T09:19:19Z"
    lastUpdateTime: "2021-09-14T09:19:19Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-09-14T09:19:13Z"
    lastUpdateTime: "2021-09-14T09:19:19Z"
    message: ReplicaSet "ngnix-5bf8f4f885" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
