apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-pv10
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.76.139
    path: "/src/nfs/kubedata"
